### ISSUE TITLE
buffer: log items are lost during navigation

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-log-activity#3]
The current implementation loses messages if place-navigation occurs before items are submitted:
The ID of messages is updated whenever messages are put into the buffer, but the buffer is reinitialized when transitioning between pages.
Instead, the buffer should be kept in the global state of the log activity, so that it may be "resumed" after navigation.

**Comment by x1B** [comment]
Here, messages are marked as processed (causing them to be lost later on):
https://github.com/LaxarJS/ax-log-activity/blob/master/ax-log-activity.js#L70

**Comment by jonaswjs** [comment]
Fixed on `master` (`3.1.0`) and on `release-3.0.x` (`3.0.2`).
