### ISSUE TITLE
allow retry of submit calls

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-log-activity#4]
Sometimes, the log service may be unreachable during a longer session (e.g. if there are connection problems, or a planned outage). To address this, users should be able to _opt-in_ to a retry process, where log submissions are retried after a configurable interval (e.g. 2 minutes by default), up to a configurable limit (e.g. 10 by default, but may be set to `null` for no limit at all).

**Comment by jonaswjs** [comment]
Implemented on `master` (`v.3.1.0`).

### New Feature

The widget now supports retrying the transmission of log messages if the first transmission failed. To enable this, the feature `logging.retry` needs to be configured with `enabled` and optional different values for the number of retries and the interval time between retries:

``` js
// in the page configuration for the widget:
{
   "features": {
      "logging": {
         "retry": {
            "enabled": true,
            "seconds": 120,
            "retries": 5
         }
      }
   }
}
```
